language: ruby
rvm:
- 2.6.6
script:
- cd spec/dummy && RAILS_ENV=test bundle exec rake db:create db:migrate
- cd ../.. && bundle exec rspec spec
deploy:
  provider: rubygems
  api_key:
    secure: SRuCVEbWNuis3IvA6TSRPRuONr8cjfV5YXKd6p0XTcW5WohCDdHeShhR2cmMq/sELB/bqgo5z6qsYuu24zryjFY4RHwmMXN2ucOEiHYZ6+PgHMT/DMP08Qw2aEsk91D0h2T8rY3VXmB3637PnX7Mgk+H4s2bn6X2WzU4lhhcSuE=
  gem: punto_pagos_rails
  on:
    tags: true
    repo: platanus/punto_pagos_rails
